param([string]$PackageRoot="art-production/test-room-v01")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
function CB([double]$v){[byte][Math]::Round([Math]::Max(0,[Math]::Min(255,$v)))}
function Lum([Drawing.Color]$c){.2126*$c.R+.7152*$c.G+.0722*$c.B}
$names=@("railing_a","rock_lip_a","hanging_cable_a","pipe_frame_a")
foreach($name in $names){$src=[Drawing.Bitmap]::new((Resolve-Path (Join-Path $PackageRoot "source/foreground/tr01_foreground_$($name)_albedo_source.png")).Path);$scale=[Math]::Min(496.0/$src.Width,240.0/$src.Height);$dw=[Math]::Round($src.Width*$scale);$dh=[Math]::Round($src.Height*$scale);$dx=[Math]::Round((512-$dw)/2);$dy=248-$dh;$scaled=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($scaled);$g.Clear([Drawing.Color]::Transparent);$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($src,[Drawing.Rectangle]::new($dx,$dy,$dw,$dh),[Drawing.Rectangle]::new(0,0,$src.Width,$src.Height),[Drawing.GraphicsUnit]::Pixel);$g.Dispose();$src.Dispose()
 $albedo=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$normal=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$emission=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$mask=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$ao=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$fade=[Drawing.Bitmap]::new(512,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb)
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt512;$x++){$p=$scaled.GetPixel($x,$y);$a=if($p.A-le4){0}elseif($p.A-ge220){255}else{CB($p.A*255/220)};if($a-eq0){$albedo.SetPixel($x,$y,[Drawing.Color]::Transparent);$normal.SetPixel($x,$y,[Drawing.Color]::Transparent);$emission.SetPixel($x,$y,[Drawing.Color]::Transparent);$mask.SetPixel($x,$y,[Drawing.Color]::Transparent);$ao.SetPixel($x,$y,[Drawing.Color]::Transparent);$fade.SetPixel($x,$y,[Drawing.Color]::Transparent);continue};$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,0,0,0));$steel=($p.B-$p.R-gt5)-and($p.B-$p.G-lt45);$metal=if($steel){188}else{30};$gloss=if($steel){56}else{18};$mask.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$metal,$gloss,0));$v=CB(190+[Math]::Min(65,(Lum $p)*.44));$ao.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$v,$v,$v));$fade.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,255,255,255))}}
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt512;$x++){$p=$albedo.GetPixel($x,$y);if($p.A-eq0){continue};$xl=[Math]::Max(0,$x-1);$xr=[Math]::Min(511,$x+1);$yu=[Math]::Max(0,$y-1);$yd=[Math]::Min(255,$y+1);$gx=((Lum $albedo.GetPixel($xr,$y))-(Lum $albedo.GetPixel($xl,$y)))/255*2.3;$gy=((Lum $albedo.GetPixel($x,$yd))-(Lum $albedo.GetPixel($x,$yu)))/255*2.3;$nx=-$gx;$ny=$gy;$len=[Math]::Sqrt($nx*$nx+$ny*$ny+1);$normal.SetPixel($x,$y,[Drawing.Color]::FromArgb($p.A,(CB(($nx/$len*.5+.5)*255)),(CB(($ny/$len*.5+.5)*255)),(CB((1/$len*.5+.5)*255))))}}
 $outs=@{albedo="approved/albedo/foreground/tr01_foreground_$($name)_albedo.png";normal="approved/normal/foreground/tr01_foreground_$($name)_normal.png";emission="approved/emission/foreground/tr01_foreground_$($name)_emission.png";mask="approved/mask/foreground/tr01_foreground_$($name)_mask.png";ao="approved/ao/foreground/tr01_foreground_$($name)_ao.png";fade="approved/mask/foreground/tr01_foreground_$($name)_fade.png"};foreach($k in $outs.Keys){$p=Join-Path $PackageRoot $outs[$k];New-Item -ItemType Directory -Force ([IO.Path]::GetDirectoryName($p))|Out-Null;(Get-Variable $k -ValueOnly).Save($p,[Drawing.Imaging.ImageFormat]::Png)};$scaled.Dispose();$albedo.Dispose();$normal.Dispose();$emission.Dispose();$mask.Dispose();$ao.Dispose();$fade.Dispose();[pscustomobject]@{Asset="TR01-FGV-$($name.ToUpper())";Canvas="512x256";PivotPixels="256,248";Result="PASS"}}
