param([string]$PackageRoot = "art-production/test-room-v01")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
function CB([double]$v){[byte][Math]::Round([Math]::Max(0,[Math]::Min(255,$v)))}
function Lum([Drawing.Color]$c){.2126*$c.R+.7152*$c.G+.0722*$c.B}
$source=Join-Path $PackageRoot "source/hero/tr01_hero_drill_a_albedo_source.png";$working=Join-Path $PackageRoot "working/hero/tr01_hero_drill_a_background_extracted.png"
if(Test-Path $working){$cut=[Drawing.Bitmap]::new((Resolve-Path $working).Path)}else{$src=[Drawing.Bitmap]::new((Resolve-Path $source).Path);$cut=[Drawing.Bitmap]::new($src.Width,$src.Height,[Drawing.Imaging.PixelFormat]::Format32bppArgb);for($y=0;$y-lt$src.Height;$y++){for($x=0;$x-lt$src.Width;$x++){$p=$src.GetPixel($x,$y);$mn=[Math]::Min($p.R,[Math]::Min($p.G,$p.B));$mx=[Math]::Max($p.R,[Math]::Max($p.G,$p.B));$a=255;if($mn-ge230){$a=0}elseif($mn-ge180-and($mx-$mn)-lt28){$a=CB((230-$mn)/50*255)};$cut.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B))}};New-Item -ItemType Directory -Force ([IO.Path]::GetDirectoryName($working))|Out-Null;$cut.Save($working,[Drawing.Imaging.ImageFormat]::Png);$src.Dispose()}
$minX=$cut.Width;$minY=$cut.Height;$maxX=-1;$maxY=-1;for($y=0;$y-lt$cut.Height;$y++){for($x=0;$x-lt$cut.Width;$x++){if($cut.GetPixel($x,$y).A-gt16){$minX=[Math]::Min($minX,$x);$maxX=[Math]::Max($maxX,$x);$minY=[Math]::Min($minY,$y);$maxY=[Math]::Max($maxY,$y)}}}
$cw=512;$ch=384;$sw=$maxX-$minX+1;$sh=$maxY-$minY+1;$scale=[Math]::Min(496.0/$sw,368.0/$sh);$dw=[Math]::Round($sw*$scale);$dh=[Math]::Round($sh*$scale);$dx=[Math]::Round(($cw-$dw)/2);$dy=$ch-8-$dh;$scaled=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($scaled);$g.Clear([Drawing.Color]::Transparent);$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($cut,[Drawing.Rectangle]::new($dx,$dy,$dw,$dh),[Drawing.Rectangle]::new($minX,$minY,$sw,$sh),[Drawing.GraphicsUnit]::Pixel);$g.Dispose();$cut.Dispose()
$albedo=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$normal=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$emission=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$mask=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$ao=[Drawing.Bitmap]::new($cw,$ch,[Drawing.Imaging.PixelFormat]::Format32bppArgb)
for($y=0;$y-lt$ch;$y++){for($x=0;$x-lt$cw;$x++){$p=$scaled.GetPixel($x,$y);$a=if($p.A-le4){0}elseif($p.A-ge220){255}else{CB($p.A*255/220)};if($a-eq0){$albedo.SetPixel($x,$y,[Drawing.Color]::Transparent);$normal.SetPixel($x,$y,[Drawing.Color]::Transparent);$emission.SetPixel($x,$y,[Drawing.Color]::Transparent);$mask.SetPixel($x,$y,[Drawing.Color]::Transparent);$ao.SetPixel($x,$y,[Drawing.Color]::Transparent);continue};$cyan=$p.G-gt70-and$p.B-gt70-and$p.G-gt$p.R*1.2;$amber=$p.R-gt100-and$p.R-gt$p.G*1.25-and$p.G-gt$p.B*1.2;$lit=$cyan-or$amber;if($lit){$peak=[Math]::Max($p.R,[Math]::Max($p.G,$p.B));$f=[Math]::Min(1,105/[Math]::Max(1,$peak));$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,(CB($p.R*$f)),(CB($p.G*$f)),(CB($p.B*$f))));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B))}else{$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,0,0,0))};$steel=($p.B-$p.R-gt5)-and($p.B-$p.G-lt45);$metal=if($steel){190}else{115};$gloss=if($steel){60}else{38};$mask.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$metal,$gloss,0));$v=CB(188+[Math]::Min(67,(Lum $p)*.44));$ao.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$v,$v,$v))}}
for($y=0;$y-lt$ch;$y++){for($x=0;$x-lt$cw;$x++){$p=$albedo.GetPixel($x,$y);if($p.A-eq0){continue};$xl=[Math]::Max(0,$x-1);$xr=[Math]::Min($cw-1,$x+1);$yu=[Math]::Max(0,$y-1);$yd=[Math]::Min($ch-1,$y+1);$gx=((Lum $albedo.GetPixel($xr,$y))-(Lum $albedo.GetPixel($xl,$y)))/255*2.5;$gy=((Lum $albedo.GetPixel($x,$yd))-(Lum $albedo.GetPixel($x,$yu)))/255*2.5;$nx=-$gx;$ny=$gy;$len=[Math]::Sqrt($nx*$nx+$ny*$ny+1);$normal.SetPixel($x,$y,[Drawing.Color]::FromArgb($p.A,(CB(($nx/$len*.5+.5)*255)),(CB(($ny/$len*.5+.5)*255)),(CB((1/$len*.5+.5)*255))))}}
$outs=@{albedo="approved/albedo/hero/tr01_hero_drill_a_albedo.png";normal="approved/normal/hero/tr01_hero_drill_a_normal.png";emission="approved/emission/hero/tr01_hero_drill_a_emission.png";mask="approved/mask/hero/tr01_hero_drill_a_mask.png";ao="approved/ao/hero/tr01_hero_drill_a_ao.png"};foreach($k in $outs.Keys){$p=Join-Path $PackageRoot $outs[$k];New-Item -ItemType Directory -Force ([IO.Path]::GetDirectoryName($p))|Out-Null;(Get-Variable $k -ValueOnly).Save($p,[Drawing.Imaging.ImageFormat]::Png)};$scaled.Dispose();$albedo.Dispose();$normal.Dispose();$emission.Dispose();$mask.Dispose();$ao.Dispose();[pscustomobject]@{Asset="TR01-HERO-DRILL-A";Canvas="512x384";Content="$($dw)x$($dh)";PivotPixels="256,376";Result="PASS"}
