param([string]$PackageRoot="art-production/test-room-v01")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
function CB([double]$v){[byte][Math]::Round([Math]::Max(0,[Math]::Min(255,$v)))}
function Lum([Drawing.Color]$c){.2126*$c.R+.7152*$c.G+.0722*$c.B}
$jobs=@(
 @{Id="TR01-LIN-RAIL-STRAIGHT-A";Name="rail_straight_a"},@{Id="TR01-LIN-RAIL-CURVE-A";Name="rail_curve_a"},@{Id="TR01-LIN-RAIL-JUNCTION-A";Name="rail_junction_a"},
 @{Id="TR01-LIN-RAIL-BROKEN-A";Name="rail_broken_a"},@{Id="TR01-LIN-PIPE-ELBOW-A";Name="pipe_elbow_a"},@{Id="TR01-LIN-CABLE-JUNCTION-A";Name="cable_junction_a"}
)
foreach($job in $jobs){
 $src=[Drawing.Bitmap]::new((Resolve-Path (Join-Path $PackageRoot "source/linear/tr01_$($job.Name)_albedo_source.png")).Path);$hasAlpha=$false
 for($y=0;$y -lt $src.Height -and -not $hasAlpha;$y+=16){for($x=0;$x -lt $src.Width;$x+=16){if($src.GetPixel($x,$y).A -lt 250){$hasAlpha=$true;break}}}
 $side=[Math]::Min($src.Width,$src.Height);$sx=[Math]::Round(($src.Width-$side)/2);$sy=[Math]::Round(($src.Height-$side)/2);$scaled=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($scaled);$g.Clear([Drawing.Color]::Transparent);$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($src,[Drawing.Rectangle]::new(0,0,256,256),[Drawing.Rectangle]::new($sx,$sy,$side,$side),[Drawing.GraphicsUnit]::Pixel);$g.Dispose();$src.Dispose()
 $albedo=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$normal=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$emission=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$mask=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$ao=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb)
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt256;$x++){$p=$scaled.GetPixel($x,$y);if($hasAlpha){$a=if($p.A-le159){0}elseif($p.A-ge240){255}else{CB(($p.A-159)*255/81)}}else{$mn=[Math]::Min($p.R,[Math]::Min($p.G,$p.B));$mx=[Math]::Max($p.R,[Math]::Max($p.G,$p.B));$a=255;if($mn-ge230){$a=0}elseif($mn-ge178-and($mx-$mn)-lt30){$a=CB((230-$mn)/52*255)}};if($a-eq0){$albedo.SetPixel($x,$y,[Drawing.Color]::Transparent);$normal.SetPixel($x,$y,[Drawing.Color]::Transparent);$emission.SetPixel($x,$y,[Drawing.Color]::Transparent);$mask.SetPixel($x,$y,[Drawing.Color]::Transparent);$ao.SetPixel($x,$y,[Drawing.Color]::Transparent);continue};$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,0,0,0));$steel=($p.B-$p.R-gt6)-and($p.B-$p.G-lt45);$metal=if($steel){190}else{35};$gloss=if($steel){58}else{18};$mask.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$metal,$gloss,0));$v=CB(195+[Math]::Min(60,(Lum $p)*.42));$ao.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$v,$v,$v))}}
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt256;$x++){$p=$albedo.GetPixel($x,$y);if($p.A-eq0){continue};$xl=[Math]::Max(0,$x-1);$xr=[Math]::Min(255,$x+1);$yu=[Math]::Max(0,$y-1);$yd=[Math]::Min(255,$y+1);$gx=((Lum $albedo.GetPixel($xr,$y))-(Lum $albedo.GetPixel($xl,$y)))/255*2.2;$gy=((Lum $albedo.GetPixel($x,$yd))-(Lum $albedo.GetPixel($x,$yu)))/255*2.2;$nx=-$gx;$ny=$gy;$len=[Math]::Sqrt($nx*$nx+$ny*$ny+1);$normal.SetPixel($x,$y,[Drawing.Color]::FromArgb($p.A,(CB(($nx/$len*.5+.5)*255)),(CB(($ny/$len*.5+.5)*255)),(CB((1/$len*.5+.5)*255))))}}
 $outs=@{albedo="approved/albedo/linear/tr01_$($job.Name)_albedo.png";normal="approved/normal/linear/tr01_$($job.Name)_normal.png";emission="approved/emission/linear/tr01_$($job.Name)_emission.png";mask="approved/mask/linear/tr01_$($job.Name)_mask.png";ao="approved/ao/linear/tr01_$($job.Name)_ao.png"};foreach($k in $outs.Keys){$p=Join-Path $PackageRoot $outs[$k];New-Item -ItemType Directory -Force ([IO.Path]::GetDirectoryName($p))|Out-Null;(Get-Variable $k -ValueOnly).Save($p,[Drawing.Imaging.ImageFormat]::Png)};$scaled.Dispose();$albedo.Dispose();$normal.Dispose();$emission.Dispose();$mask.Dispose();$ao.Dispose();[pscustomobject]@{Asset=$job.Id;Canvas="256x256";PivotPixels="128,128";Result="PASS"}
}
