param([string]$PackageRoot="art-production/test-room-v01")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
function CB([double]$v){[byte][Math]::Round([Math]::Max(0,[Math]::Min(255,$v)))}
function Lum([Drawing.Color]$c){.2126*$c.R+.7152*$c.G+.0722*$c.B}
$names=@("crate_a","toolbox_a","rock_a","mineral_a","barrel_a","papers_a","cable_spool_a","beams_a","bucket_a","hardware_a")
foreach($name in $names){
 $existing=Join-Path $PackageRoot "approved/albedo/decoration/tr01_dec_$($name)_albedo.png";if(Test-Path $existing){continue}
 $src=[Drawing.Bitmap]::new((Resolve-Path (Join-Path $PackageRoot "source/decoration/tr01_dec_$($name)_albedo_source.png")).Path);$hasAlpha=$false;for($y=0;$y -lt $src.Height -and -not $hasAlpha;$y+=16){for($x=0;$x -lt $src.Width;$x+=16){if($src.GetPixel($x,$y).A -lt 250){$hasAlpha=$true;break}}}
 $scale=[Math]::Min(240.0/$src.Width,240.0/$src.Height);$dw=[Math]::Round($src.Width*$scale);$dh=[Math]::Round($src.Height*$scale);$dx=[Math]::Round((256-$dw)/2);$dy=248-$dh;$scaled=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($scaled);$g.Clear([Drawing.Color]::Transparent);$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($src,[Drawing.Rectangle]::new($dx,$dy,$dw,$dh),[Drawing.Rectangle]::new(0,0,$src.Width,$src.Height),[Drawing.GraphicsUnit]::Pixel);$g.Dispose();$src.Dispose()
 $albedo=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$normal=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$emission=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$mask=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$ao=[Drawing.Bitmap]::new(256,256,[Drawing.Imaging.PixelFormat]::Format32bppArgb)
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt256;$x++){$p=$scaled.GetPixel($x,$y);if($hasAlpha){$a=if($p.A-le159){0}elseif($p.A-ge240){255}else{CB(($p.A-159)*255/81)}}else{$mn=[Math]::Min($p.R,[Math]::Min($p.G,$p.B));$mx=[Math]::Max($p.R,[Math]::Max($p.G,$p.B));$a=255;if($mn-ge230){$a=0}elseif($mn-ge178-and($mx-$mn)-lt30){$a=CB((230-$mn)/52*255)}};if($a-eq0){$albedo.SetPixel($x,$y,[Drawing.Color]::Transparent);$normal.SetPixel($x,$y,[Drawing.Color]::Transparent);$emission.SetPixel($x,$y,[Drawing.Color]::Transparent);$mask.SetPixel($x,$y,[Drawing.Color]::Transparent);$ao.SetPixel($x,$y,[Drawing.Color]::Transparent);continue};$lit=$name-eq"mineral_a"-and$p.R-gt80-and$p.B-gt65-and$p.R-gt$p.G*1.3;if($lit){$peak=[Math]::Max($p.R,$p.B);$f=[Math]::Min(1,105/[Math]::Max(1,$peak));$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,(CB($p.R*$f)),(CB($p.G*$f)),(CB($p.B*$f))));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B))}else{$albedo.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$p.R,$p.G,$p.B));$emission.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,0,0,0))};$steel=($p.B-$p.R-gt5)-and($p.B-$p.G-lt45);$metal=if($steel){185}else{35};$gloss=if($steel){58}elseif($lit){115}else{20};$mask.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$metal,$gloss,0));$v=CB(194+[Math]::Min(61,(Lum $p)*.42));$ao.SetPixel($x,$y,[Drawing.Color]::FromArgb($a,$v,$v,$v))}}
 for($y=0;$y-lt256;$y++){for($x=0;$x-lt256;$x++){$p=$albedo.GetPixel($x,$y);if($p.A-eq0){continue};$xl=[Math]::Max(0,$x-1);$xr=[Math]::Min(255,$x+1);$yu=[Math]::Max(0,$y-1);$yd=[Math]::Min(255,$y+1);$gx=((Lum $albedo.GetPixel($xr,$y))-(Lum $albedo.GetPixel($xl,$y)))/255*2.3;$gy=((Lum $albedo.GetPixel($x,$yd))-(Lum $albedo.GetPixel($x,$yu)))/255*2.3;$nx=-$gx;$ny=$gy;$len=[Math]::Sqrt($nx*$nx+$ny*$ny+1);$normal.SetPixel($x,$y,[Drawing.Color]::FromArgb($p.A,(CB(($nx/$len*.5+.5)*255)),(CB(($ny/$len*.5+.5)*255)),(CB((1/$len*.5+.5)*255))))}}
 $outs=@{albedo="approved/albedo/decoration/tr01_dec_$($name)_albedo.png";normal="approved/normal/decoration/tr01_dec_$($name)_normal.png";emission="approved/emission/decoration/tr01_dec_$($name)_emission.png";mask="approved/mask/decoration/tr01_dec_$($name)_mask.png";ao="approved/ao/decoration/tr01_dec_$($name)_ao.png"};foreach($k in $outs.Keys){$p=Join-Path $PackageRoot $outs[$k];New-Item -ItemType Directory -Force ([IO.Path]::GetDirectoryName($p))|Out-Null;(Get-Variable $k -ValueOnly).Save($p,[Drawing.Imaging.ImageFormat]::Png)};$scaled.Dispose();$albedo.Dispose();$normal.Dispose();$emission.Dispose();$mask.Dispose();$ao.Dispose();[pscustomobject]@{Asset="TR01-DEC-$($name.ToUpper())";Canvas="256x256";PivotPixels="128,248";Result="PASS"}
}
